export function formatEffectif(tranche: string | null): string {
  const map: Record<string, string> = {
    "00": "0 salarié",
    "01": "1-2",
    "02": "3-5",
    "03": "6-9",
    "11": "10-19",
    "12": "20-49",
    "21": "50-99",
    "22": "100-199",
    "31": "200-249",
    "32": "250-499",
    "41": "500-999",
    "42": "1 000-1 999",
    "51": "2 000-4 999",
    "52": "5 000-9 999",
    "53": "10 000+",
  };
  return tranche ? (map[tranche] ?? tranche) : "N/A";
}

export function formatNatureJuridique(code: string | null): string {
  if (!code) return "N/D";
  const map: Record<string, string> = {
    "1000": "Entrepreneur individuel",
    "2110": "Indivision",
    "2120": "Société créée de fait",
    "2210": "Groupement de droit privé non doté de la personnalité morale",
    "3110": "Représentation ou agence commerciale d'état ou organisme public étranger immatriculé au RCS",
    "3120": "Société commerciale étrangère immatriculée au RCS",
    "4110": "Congrégation",
    "4120": "Association loi 1901 ou assimilé",
    "4130": "Fondation",
    "5191": "Société de caution mutuelle",
    "5202": "Société en nom collectif",
    "5306": "Société en commandite simple",
    "5307": "Société en commandite par actions",
    "5308": "Société à responsabilité limitée (sans désignation d'associé unique ou de gérance-pluralité)",
    "5310": "Société à responsabilité limitée",
    "5370": "Société à responsabilité limitée (avec conseil d'administration)",
    "5385": "Société d'exercice libéral à responsabilité limitée",
    "5410": "SA à conseil d'administration (s.a.i.)",
    "5415": "SA à conseil d'administration",
    "5422": "SA à directoire (s.a.i.)",
    "5426": "SA à directoire",
    "5430": "SA à conseil de surveillance",
    "5443": "SA coopérative à conseil d'administration (s.a.i.)",
    "5451": "SA coopérative à directoire (s.a.i.)",
    "5453": "SA coopérative à conseil de surveillance (s.a.i.)",
    "5458": "SA coopérative à directoire",
    "5460": "SA coopérative à conseil de surveillance",
    "5470": "Société anonyme coopérative ouvrière de production (SCOP)",
    "5485": "Société d'exercice libéral à forme anonyme",
    "5498": "EURL",
    "5499": "SARL",
    "5505": "SA à participation ouvrière à conseil d'administration",
    "5510": "SAS",
    "5515": "SAS, société par actions simplifiée",
    "5520": "SASU",
    "5585": "Société d'exercice libéral par action simplifiée",
    "5600": "Autre SA à participation ouvrière",
    "5605": "SA coopérative à conseil d'administration",
    "5610": "Société anonyme à participation ouvrière coopérative de production",
    "5615": "Société coopérative ouvrière de production et de crédit",
    "5620": "Société anonyme coopérative de banque populaire",
    "5710": "SAS",
    "5720": "SASU",
    "5900": "Société civile",
    "6100": "Caisse d'épargne et de prévoyance",
    "6210": "Groupement européen d'intérêt économique",
    "6220": "Groupement d'intérêt économique",
    "6316": "Coopérative d'utilisation de matériel agricole en commun (CUMA)",
    "6317": "Société coopérative agricole",
    "6318": "Union de sociétés coopératives agricoles",
    "6411": "Mutualité",
    "6521": "Caisse de retraite et de prévoyance",
    "6532": "Établissement public local à caractère industriel ou commercial",
    "6533": "Établissement public à caractère industriel ou commercial relevant d'une collectivité territoriale",
    "6534": "Autre établissement public à caractère industriel ou commercial",
    "6535": "I.E.G. (entreprises relevant de la loi du 8 avril 1946)",
    "6536": "Caisse Nationale de Crédit Agricole",
    "6537": "Banque de France",
    "6538": "Caisse d'épargne et de prévoyance",
    "6539": "Autre établissement public à caractère financier",
    "6540": "Caisse des dépôts et consignations",
    "6541": "Établissement public des postes et des télécommunications",
    "6542": "La Poste",
    "6543": "France Telecom",
    "6544": "Établissement public national à caractère industriel ou commercial doté d'un statut particulier",
    "6545": "Régie d'une collectivité locale à caractère industriel ou commercial",
    "6546": "Établissement public national à caractère industriel ou commercial n.c.a.",
    "6551": "Société nationale",
    "6554": "Établissement public national à caractère administratif",
    "6558": "Établissement public régional à caractère administratif",
    "6560": "Caisse nationale de Sécurité sociale",
    "6561": "Organisme gérant un régime de protection sociale à adhésion obligatoire",
    "6562": "Organisme mutualiste",
    "6563": "Comité d'entreprise",
    "6564": "Organisme professionnel",
    "6565": "Organisme de retraite à adhésion non obligatoire",
    "6600": "Fondation",
    "7111": "Autorité constitutionnelle",
    "7112": "Autorité administrative indépendante",
    "7113": "Ministère",
    "7120": "Service central d'un ministère",
    "7150": "Service déconcentré à compétence nationale d'un ministère",
    "7160": "Service déconcentré territorial unique d'un ministère",
    "7171": "Service déconcentré territorial de la direction générale des impôts",
    "7172": "Service déconcentré territorial de la direction générale des douanes",
    "7179": "Autre service déconcentré territorial d'un ministère (non prévu ailleurs)",
    "7190": "Autre service de l'Etat",
    "7210": "Commune",
    "7220": "Département",
    "7225": "Territoire d'Outre-Mer",
    "7229": "Autre collectivité territoriale",
    "7230": "Région",
    "7312": "Commune associée résultant d'une fusion de communes",
    "7313": "Section de commune",
    "7314": "Ensemble urbain",
    "7321": "Association syndicale autorisée",
    "7322": "Association foncière urbaine",
    "7323": "Association foncière de remembrement",
    "7331": "Établissement public local d'enseignement",
    "7340": "Chambre consulaire",
    "7341": "Chambre de commerce et d'industrie",
    "7342": "Chambre d'agriculture",
    "7343": "Chambre de métiers",
    "7344": "Bureau de redistribution",
    "7345": "Greffe du tribunal de commerce",
    "7346": "Établissement public consulaire n.c.a.",
    "7348": "Centre technique industriel ou comité professionnel du développement économique",
    "7349": "Autre organisme professionnel",
    "7351": "Service départemental d'incendie et de secours (SDIS)",
    "7361": "Établissement public local à caractère administratif (excl. collège et lycée)",
    "7362": "Lycée public, établissement de formation continue",
    "7363": "Collège public",
    "7364": "Établissement public local d'enseignement et de formation professionnelle agricoles",
    "7365": "CIAS et CCAS",
    "7366": "Caisse des écoles",
    "7371": "Office public d'habitation à loyer modéré (OPHLM)",
    "7372": "Office public d'aménagement et de construction (OPAC)",
    "7378": "Autre établissement public administratif local",
    "7379": "Autre établissement public administratif local n.c.a.",
    "7381": "Organisme consulaire",
    "7382": "Organisme professionnel des branches d'activité du secteur marchand",
    "7383": "Organisme syndical",
    "7384": "Organisme national professionnel du secteur de l'économie sociale",
    "7385": "Organisme d'employeurs",
    "7389": "Autre organisme n.c.a.",
    "7410": "Groupement de collectivités",
    "7430": "Communauté urbaine",
    "7450": "Communauté de communes",
    "7470": "Communauté de villes",
    "7490": "Syndicat mixte",
    "7510": "Commission syndicale pour la gestion des biens indivis des communes",
    "7520": "Pays",
    "7530": "Communauté d'agglomération",
    "7540": "Métropole",
    "7550": "Communauté de communes",
    "7600": "Établissement public administratif de l'État à compétence nationale",
    "7700": "Groupement d'intérêt public (GIP)",
    "7900": "Autre personne morale de droit administratif",
    "9110": "Syndicat de copropriété",
    "9150": "Association syndicale libre",
    "9210": "Association non déclarée",
    "9220": "Association déclarée",
    "9221": "Association déclarée d'utilité publique",
    "9222": "Association déclarée sous régime Alsace-Moselle",
    "9223": "Association d'Alsace-Moselle non déclarée",
    "9224": "Association reconnue d'utilité publique régie par le code local Alsace-Moselle",
    "9230": "Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)",
    "9240": "Congrégation",
    "9260": "Association étrangère",
    "9300": "Fondation",
    "9900": "Autre personne morale de droit privé",
    "9970": "Groupement de droit privé",
  };
  return map[code] ?? code;
}

// NAF section codes (A–U) to French labels
const NAF_SECTIONS: Record<string, string> = {
  A: "Agriculture, sylviculture et pêche",
  B: "Industries extractives",
  C: "Industrie manufacturière",
  D: "Production et distribution d'électricité, de gaz, de vapeur et d'air conditionné",
  E: "Production et distribution d'eau ; assainissement, gestion des déchets et dépollution",
  F: "Construction",
  G: "Commerce ; réparation d'automobiles et de motocycles",
  H: "Transports et entreposage",
  I: "Hébergement et restauration",
  J: "Information et communication",
  K: "Activités financières et d'assurance",
  L: "Activités immobilières",
  M: "Activités spécialisées, scientifiques et techniques",
  N: "Activités de services administratifs et de soutien",
  O: "Administration publique",
  P: "Enseignement",
  Q: "Santé humaine et action sociale",
  R: "Arts, spectacles et activités récréatives",
  S: "Autres activités de services",
  T: "Activités des ménages en tant qu'employeurs",
  U: "Activités extra-territoriales",
};

export function formatNafSection(code: string | null): string {
  if (!code) return "N/D";
  const section = code.charAt(0).toUpperCase();
  return NAF_SECTIONS[section] ?? code;
}
